version: '3.8'

services:
  agent_emploi:
    build: .
    container_name: bot_candidatures_daniel
    restart: unless-stopped
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./db_data:/app/data